### ISSUE TITLE
Migrate to Vultr

### ISSUE THREAD

**Issue by leviem1** [Snowy-Peak-Systems/CodeMiners-Issues#46]
**Is your service request related to a problem? Please describe.**
Server is running well, but a bit expensive.

**Describe the solution you'd like**
Migrate to Vultr 4CPU, 8GB RAM, 160GB storage plan.

**Describe alternatives you've considered**
Many other Minecraft hosts are available, but many will not give us the control and power we need. This is also much cheaper that AWS, which is designed for small web apps, not game servers. The biggest difference is made between the processor frequencies, as Minecraft needs a higher frequency.

**Additional context**
Promo: https://www.vultr.com/promo/try50/
Vultr plans: https://www.vultr.com/products/cloud-compute/
AWS Benchmarks: https://browser.geekbench.com/v4/cpu/search?utf8=%E2%9C%93&q=t3.large

**Comment by leviem1** [comment]
Waiting on account creation

**Comment by bassettmason** [comment]
Working on it right now
